- name: all
  hosts: masters:nodes:etcd:lb:nfs:dns
  roles:
  - prepare

- name: Docker host configuration
  hosts: masters:nodes
  roles:
  - os

- name: Install DNS
  hosts: dns
  roles:
  - dns

- name: Node DNS configuration
  hosts: masters:nodes
  roles:
  - node-dns

- name: LB DNS configuration
  hosts: lb
  roles:
  - lb-dns

- name: Prepare common configuration
  hosts: masters:nodes:etcd:lb:nfs:dns
  roles:
  - common

- name: Install Docker
  hosts: masters:nodes
  roles:
  - docker

