- name: all
  hosts: masters:nodes:etcd:lb:nfs

- name: docker host
  hosts: masters:nodes
  roles:
  - os

- name: dns
  hosts: lb
  roles:
  - dns

- name: docker host
  hosts: masters:nodes
  roles:
  - node-dns

- name: all
  hosts: masters:nodes:etcd:lb:nfs
  roles:
  - common

- name: docker host
  hosts: masters:nodes
  roles:
#  - docker

