#- name: Enable CentOS CR repository
#  copy:
#    src:  CentOS-CR.repo
#    dest: /etc/yum.repos.d/CentOS-CR.repo
#  when: 
#  - ansible_distribution == "CentOS" 
#  - ansible_distribution_version | version_compare('7.4.1708', '<')

- block:
  - name: Kernel Pacakge update
    package:
      name: "{{item}}"
      state: latest
    with_items:
    - kernel
    - kernel-tools
    register: is_kernel_update

  - name: reboot!
    become: yes
    shell: sleep 2 && /usr/sbin/shutdown -r now
    async: 1
    poll:  0
    when: is_kernel_update.changed
  #  ignore_errors: true
 
  - name: wait for SSH port down
    local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=30 timeout=180
    become: false
 
  when: ansible_kernel is version_compare('3.10.0-693', '<')
  tags: kernel_update

- name: Pacakge update
  package:
    name: "{{item}}"
    state: latest
  with_items:
  - dnsmasq

- name: Disable Change Hostname by waagent (for Azure)
  replace:
    path: /etc/waagent.conf
    regexp: 'Provisioning.MonitorHostName=y'
    replace: 'Provisioning.MonitorHostName=n'
  when: ansible_system_vendor == "Microsoft Corporation"

- name: Set hostname
  shell: |
    /usr/bin/hostnamectl set-hostname --static "{{ inventory_hostname }}"

- name: Add hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

