- name: Enable CentOS CR repository
  copy:
    src:  CentOS-CR.repo
    dest: /etc/yum.repos.d/CentOS-CR.repo
  when: ansible_distribution == "CentOS"

- name: Yum update
  yum:
    name: "{{item}}"
    state: latest
  with_items:
  - kernel
  - firewalld

- name: Set hostname
  shell: |
    /usr/bin/hostnamectl set-hostname "{{ ansible_fqdn }}"

- name: reboot!
  command: /usr/sbin/shutdown -r now

- name: wait for SSH port down
  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped

- name: wait for SSH port up
  wait_for: host={{ inventory_hostname }} port=22 state=started delay=30
  delegate_to: 127.0.0.1
