- name: Create OpenShift Directory
  file:
    path: "{{item}}"
    state: directory
    mode:  0755
  with_items:
  - /var/lib/origin/openshift.local.volumes
  - /var/lib/origin/openshift.local.config
  - /var/lib/origin/openshift.local.etcd



- name: Start Firewalld
  service:
    name: firewalld
    state: started 

- name: Check OpenShift
  stat:
    path: "{{install_dir}}"
  register: st

- name: Get OpenShift Binary
  unarchive:
    src: "{{openshift_tgz}}"
    dest: /tmp
    remote_src: True
  when: st.stat.islnk is not defined

- name: Place OpenShift 
  shell: |
    mv /tmp/{{openshift_extract_dir}} {{install_dir}} 
  when: st.stat.islnk is not defined

- name: Check OpenShift
  stat:
    path: "{{install_dir}}/openshift.local.config/master/admin.kubeconfig"
  register: st

#- block: 
#  - name: Run OpenShift Tempolary
#    shell: |
#      {{install_dir}}/openshift start --public-master=https://{{network.portal}}:8443 --master=https://localhost:8443 --dns='tcp://0.0.0.0:53'
#    args:
#      chdir: "{{install_dir}}"
#    async: 10
#    poll:  5
#    register: os_temp
#    ignore_errors: yes
#
#  - name: Check OpenShift Timeout
#    async_status: jid={{ os_temp.ansible_job_id }}
#    register: job_result
#    until: job_result.finished
#    when: os_temp.failed
#    ignore_errors: yes
#
#  - name: fixed admin.kubeconfig permission
#    file:
#      path: "{{install_dir}}/openshift.local.config/master/admin.kubeconfig"
#      owner: root
#      group: root
#      mode: 0644
#
#  when: st.stat.islnk is not defined

- name: Allow portal access
  firewalld:
    zone: public
    port: 8443/tcp
    permanent: true
    state: enabled

- name: Allow api access
  firewalld:
    zone: public
    port: 443/tcp
    permanent: true
    state: enabled

- name: Allow DNS access
  firewalld:
    zone: public
    port: 8053/udp
    permanent: true
    state: enabled

- name: Allow DNS access
  firewalld:
    zone: public
    port: 53/udp
    permanent: true
    state: enabled

- name: Install OpenShift Systemd file 1/2
  template:
    src: systemd/openshift.service
    dest: /etc/systemd/system/multi-user.target.wants/openshift.service
    owner: root
    group: root
    mode: 0644

- name: Run OpenShift Cluster
  shell: |
    /opt/openshift/oc cluster up --public-hostname={{ network.portal }}

- name: Set Docker interface IP
  shell: |
    ip addr add 172.17.0.1/16 dev docker0

#- name: Install OpenShift Systemd file 2/2
#  template:
#    src: systemd/openshift.j2
#    dest: /etc/sysconfig/openshift
#    owner: root
#    group: root
#    mode: 0644

#- name: Start OpenShift Service
#  systemd:
#    daemon-reload: yes
#    name: openshift

#- name: Add Registry
#  shell: |
#    "{{install_dir}}/oadm registry --config={{install_dir}}/openshift.local.config/master/admin.kubeconfig --service-account=registry --images='registry.access.redhat.com/openshift3/ose-${component}:${version}' --selector='region=infra'
