- name: Create DNS config files for OpenShift
  file:
    path: /etc/origin/node/resolv.conf
    state: directory
    owner: root
    group: root
    mode:  0755

- name: Create external dns config
  template:
    src: dnsmasq/external-dns.conf.j2
    dest: /etc/dnsmasq.d/external-dns.conf
    owner: root
    group: root
    mode: 0644

- name: Stop firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: no

    