- name: Install dnsmasq
  yum:
    name: dnsmasq
    state: latest

- name: Create hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Upstream DNS
  template:
    src: origin.conf.j2
    dest: /etc/dnsmasq.d/origin.conf

- name: Start dnsmasq
  service:
    name: dnsmasq
    state: restarted
    enabled: yes

- name: Allow DNS Port
  iptables:
    chain: INPUT
    protocol: udp
    destination_port: 53
    ctstate: NEW
#    syn: match
    jump: ACCEPT
    comment: Accept DNS

- name: Add dns port
  firewalld:
    service: dns
    state: enabled
    permanent: yes

#- name: Restart firewalld
#  service:
#    name: firewalld
#    state: restarted
