- name: Install dnsmasq
  yum:
    name: dnsmasq
    state: latest

- name: Create hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Update resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: Upstream DNS
  template:
    src: upstream-dns.conf.j2
    dest: /etc/dnsmasq.d/upstream-dns.conf

- name: Start dnsmasq
  service:
    name: dnsmasq
    state: restarted
    enabled: yes

- name: Allow DNS Port
  iptables:
    chain: INPUT
    protocol: udp
    destination_port: 53
    ctstate: NEW
#    syn: match
    jump: ACCEPT
    comment: Accept DNS

- name: Add dns port
  firewalld:
    service: dns
    state: enabled
    permanent: yes

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted
