- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: yes

- name: Install RPMS
  package:
    name: "{{item}}"
    state: latest
  with_items:
  - PyYAML
  - python-ipaddress
  - iptables
  - iptables-services

- name: Enable iptables
  service:
    name: iptables
    state: started
    enabled: yes

- name: Add origin yum repository
  yum_repository:
    name: origin
    description: OpenShift Origin YUM repo
    file: origin
    baseurl: http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/
    gpgcheck: no

- name: Update resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
