- name: Disable dnsmasq
  service: 
    name: dnsmasq
    enabled: no
    state: stopped

- name: Install required packages
  yum:
    name: "{{item}}"
    state: latest
  with_items:
  - wget
  - git
  - net-tools
  - bind-utils
  - iptables-services
  - bridge-utils
  - bash-completion
  - kexec-tools
  - sos
  - psacct

- name: Install Docker
  yum:
    name: docker-latest
    state: latest

- name: config docker
  template:
    src: docker.j2
    dest: /etc/sysconfig/docker-latest
    owner: root
    group: root
    mode: 0644

- name: config docker-network
  template:
    src: docker-network.j2
    dest: /etc/sysconfig/docker-latest-network
    owner: root
    group: root
    mode: 0644

- name: config docker-storage
  copy:
    src: docker-storage
    dest: /etc/sysconfig/docker-latest-storage
    owner: root
    group: root
    mode: 0644

- name: Create /etc/sysconfig/docker
  file:
    path: /etc/sysconfig/docker
    state: file
    mode:  0755
 
- name: Restart Docker Service
  service:
    name: docker-latest
    enabled: yes
    state: restarted
