- name: Disable dnsmasq
  service: 
    name: dnsmasq
    enabled: no
    state: stopped

- name: Install required packages
  package:
    name: "{{item}}"
    state: latest
  with_items:
  - net-tools
  - bind-utils
  - iptables-services
  - bridge-utils
  - bash-completion
  - kexec-tools
  - sos
  - psacct

- name: Install Docker
  package:
    name: docker
    state: latest

- name: Config /etc/sysconfig/docker
  template:
    src: docker.j2
    dest: /etc/sysconfig/docker
    owner: root
    group: root
    mode: 0644

- name: Config /etc/sysconfig/docker-network
  template:
    src: docker-network.j2
    dest: /etc/sysconfig/docker-network
    owner: root
    group: root
    mode: 0644

- name: Config /etc/sysconfig/docker-storage
  copy:
    src: docker-storage
    dest: /etc/sysconfig/docker-storage
    owner: root
    group: root
    mode: 0644

- name: Config /etc/sysconfig/docker-storage-setup
  template:
    src: docker-storage-setup.j2
    dest: /etc/sysconfig/docker-storage-setup
    owner: root
    group: root
    mode: 0644

- name: Restart Docker Service
  service:
    name: docker
    enabled: yes
    state: restarted
