- name: Install dnsmasq
  yum:
    name: dnsmasq
    state: latest

- name: dnsmasq config
  template:
    src: upstream-dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/upstream-dnsmasq.conf

- name: Upstream DNS
  lineinfile:
    path: /etc/dnsmasq.d/upstream-dns.conf
    line: "server={{ dns }}"
    create: yes

- name: Create /etc/origin/node
  file:
    path: /etc/origin/node
    state: directory
    recurse: yes

- name: Create Openshift resolv.conf
  template:
    src: origin-resolv.conf.j2
    dest: /etc/origin/node/resolv.conf

- name: Restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
    enabled: yes
