- name: Install dnsmasq
  yum:
    name: dnsmasq
    state: latest

- name: Upstream DNS
  template:
    src: origin-upstream-dns.conf.j2
    dest: /etc/dnsmasq.d/origin-upstream-dns.conf

- name: SkyDNS for OpenShift internal hostname
  template:
    src: node-dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/node-dnsmasq.conf

#- name: Upstream DNS
#  lineinfile:
#    path: /etc/dnsmasq.d/origin-upstream-dns.conf
#    line: "server={{ hostvars[groups['lb'][0]].ansible_eth0.ipv4.address }}"
#    create: yes

- name: Create /etc/origin/node
  file:
    path: /etc/origin/node
    state: directory
    recurse: yes

- name: Create Openshift resolv.conf
  template:
    src: origin-resolv.conf.j2
    dest: /etc/origin/node/resolv.conf

- name: Update resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: Restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
    enabled: yes
